cumurupraias/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve as serve_static
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from ondecomer.sitemaps import OndeComerSitemap
from home.sitemaps import HomeSitemap
from ondeficar.sitemaps import OndeFicarSitemap
from passeios.sitemaps import PasseioSitemap
from praias.sitemaps import PraiaSitemap
from servicos.sitemaps import ServicoSitemap
from artesanatos.sitemaps import ArtesanatoSitemap

from home import views

sitemaps = {
    'ondecomer': OndeComerSitemap,
    'home':HomeSitemap,
    'ondeficar':OndeFicarSitemap,
    'passios':PasseioSitemap,
    'praias':PraiaSitemap,
    'servicos':ServicoSitemap,
    'artesanatos':ArtesanatoSitemap,

}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^$', views.index, name='index'),
    url(r'^como-chegar$', views.comochegar, name='comochegar'),
    url(r'^onde-comer/', include('ondecomer.urls', namespace='ondecomer')),
    url(r'^onde-ficar/', include('ondeficar.urls', namespace='ondeficar')),
    url(r'^passeios/', include('passeios.urls', namespace='passeios')),
    url(r'^compras/', include('artesanatos.urls', namespace='artesanatos')),
    url(r'^servicos/', include('servicos.urls', namespace='servicos')),
    url(r'^praias/', include('praias.urls', namespace='praias')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
    name='django.contrib.sitemaps.views.sitemap'),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

ondecomer/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.listar, name='listar'),
    url(r'^(?P<slug>[\w_-]+)$', views.ondecomer, name='ondecomer'),
]

passeios/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.listar, name='listar'),
    url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'),
    url(r'^(?P<slug>[\w_-]+)$', views.passeio, name='passeio'),
]

praias/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.listar, name='listar'),
    url(r'^(?P<slug>[\w_-]+)$', views.praia, name='praia'),
]

servicos/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.listar, name='listar'),
    url(r'^(?P<slug>[\w_-]+)$', views.category, name='category'),
    url(r'^(?P<slug>[\w_-]+)$', views.servico, name='servico'),
]

artesanatos/models.py
# coding=utf-8
from django.db import models
from django.core.urlresolvers import reverse

class CategoryArtesanato(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Categoria_Artesanato'
        verbose_name_plural = 'Categoria_Artesanato'
        ordering = ['name']
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('artesanatos:category', kwargs={'slug': self.slug})



class Artesanato(models.Model):
    name = models.CharField('Nome', max_length=100, blank=True)
    slug = models.SlugField('Identificador', max_length=100, blank=True)
    category = models.ForeignKey('artesanatos.CategoryArtesanato', verbose_name='Categoria_Artesanato')
    image_1 = models.ImageField(upload_to='artesanatos', verbose_name='Imagem_1', null=True, blank=True)
    decription_1 = models.CharField('Descrição-1', max_length=100, blank=True)
    image_2 = models.ImageField(upload_to='artesanatos', verbose_name='Imagem_2', null=True, blank=True)
    decription_2 = models.CharField('Descrição-2', max_length=100, blank=True)
    image_3 = models.ImageField(upload_to='artesanatos', verbose_name='Imagem_3', null=True, blank=True)
    decription_3 = models.CharField('Descrição-3', max_length=100, blank=True)
    image_4 = models.ImageField(upload_to='artesanatos', verbose_name='Imagem_4', null=True, blank=True)
    decription_4 = models.CharField('Descrição-4', max_length=100, blank=True)

    image_5 = models.ImageField(upload_to='artesanatos', verbose_name='Imagem_5', null=True, blank=True)
    decription_5 = models.CharField('Descrição-5', max_length=100, blank=True)
    image_6 = models.ImageField(upload_to='artesanatos', verbose_name='Imagem_6', null=True, blank=True)
    decription_6 = models.CharField('Descrição-6', max_length=100, blank=True)
    image_7 = models.ImageField(upload_to='artesanatos', verbose_name='Imagem_7', null=True, blank=True)
    decription_7 = models.CharField('Descrição-7', max_length=100, blank=True)
    image_8 = models.ImageField(upload_to='artesanatos', verbose_name='Imagem_8', null=True, blank=True)
    decription_8 = models.CharField('Descrição-8', max_length=100, blank=True)
    image_9 = models.ImageField(upload_to='artesanatos', verbose_name='Imagem_9', null=True, blank=True)
    decription_9 = models.CharField('Descrição-9', max_length=100, blank=True)
    image_10 = models.ImageField(upload_to='artesanatos', verbose_name='Imagem_10', null=True, blank=True)
    decription_10 = models.CharField('Descrição-10', max_length=100, blank=True)

    description = models.TextField('Descrição', blank=True)
    address = models.CharField('Endereço', max_length=100, blank=True)
    email = models.EmailField('E-mail', max_length=50, blank=True)
    contact = models.CharField('Contato', max_length=100, blank=True)
    site = models.CharField('Site', max_length=100, blank=True)
    link = models.CharField('link',max_length=120, blank=True)


    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name='Artesanato'
        verbose_name_plural = 'Artesanatos'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('artesanatos:artesanato', kwargs={'slug': self.slug})

class ImageArtesanato(models.Model):
    image = models.ImageField(upload_to='images-capa', verbose_name='Imagem', null=True, blank=True)
    decription = models.CharField('Descrição', max_length=100, blank=True)
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name='Imagem_Artesanato'

core/models.py
from django.db import models

# Create your models here.

servicos/models.py
# coding=utf-8

from django.db import models

from django.db import models
from django.core.urlresolvers import reverse

class CategoryServico(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)
    image = models.ImageField(upload_to='images-servicos', verbose_name='Imagem', null=True, blank=True)
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Categoria_Servico'
        verbose_name_plural = 'Categoria_Servicos'
        ordering = ['name']
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('servicos:category', kwargs={'slug': self.slug})



class Servico(models.Model):
    name = models.CharField('Nome', max_length=100, blank=True)
    slug = models.SlugField('Identificador', max_length=100, blank=True)
    category = models.ForeignKey('servicos.CategoryServico', verbose_name='Categoria_Servicos')
    image_servico = models.ImageField(upload_to='images-capa', verbose_name='Imagem', null=True, blank=True)
    decription_image = models.CharField('Descrição_imagem', max_length=100, blank=True)
    texto = models.TextField('Descrição', blank=True)
    address = models.CharField('Endereço', max_length=100, blank=True)
    email = models.EmailField('E-mail', max_length=50, blank=True)
    contact = models.CharField('Contato', max_length=100, blank=True)
    site = models.CharField('Site', max_length=100, blank=True)
    link = models.CharField('link',max_length=120, blank=True)


    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name='Servico'
        verbose_name_plural = 'Servicos'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('servicos:servico', kwargs={'slug': self.slug})


class ImageServico(models.Model):
    image = models.ImageField(upload_to='images-capa', verbose_name='Imagem', null=True, blank=True)
    decription = models.CharField('Descrição', max_length=100, blank=True)
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name='Imagem_Servico'

artesanatos/views.py
# coding=utf-8


from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Artesanato, CategoryArtesanato, ImageArtesanato


class ListarListView(generic.ListView):
    model = Artesanato
    template_name = 'artesanatos/lista.html'
    context_object_name = 'object_list'
    paginate_by = 8

    def get_context_data(self, **kwargs):
        context = super(ListarListView, self).get_context_data(**kwargs)
        context['capa'] = ImageArtesanato.objects.all()
        return context


listar = ListarListView.as_view()

class CategoryListView(generic.ListView):
    template_name = 'artesanatos/descricao.html'
    context_object_name = 'object_list'
    paginate_by = 8

    def get_queryset(self):
        return Artesanato.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(CategoryArtesanato, slug=self.kwargs['slug'])
        return context

category = CategoryListView.as_view()

def artesanato(request, slug):
    artesanato = Artesanato.objects.get(slug=slug)
    context = {
        'artesanato': artesanato
    }
    return render(request, 'artesanatos/slide.html', context)

core/views.py
from django.shortcuts import render

# Create your views here.

ondecomer/views.py
# coding=utf-8

from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import OndeComer, CategoryOndeComer, ImageOndecomer


class ListarListView(generic.ListView):
    model = OndeComer
    template_name = 'ondecomer/lista.html'
    context_object_name = 'object_list'
    paginate_by = 8

    def get_context_data(self, **kwargs):
        context = super(ListarListView, self).get_context_data(**kwargs)
        context['capa'] = ImageOndecomer.objects.all()
        return context

listar = ListarListView.as_view()

class CategoryListView(generic.ListView):
    template_name = 'ondecomer/descricao.html'
    context_object_name = 'object_list'
    paginate_by = 8

    def get_queryset(self):
        return OndeComer.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(CategoryOndeComer, slug=self.kwargs['slug'])
        context['capa'] = ImageOndecomer.objects.all()
        return context

category = CategoryListView.as_view()

def ondecomer(request, slug):
    ondecomer = OndeComer.objects.get(slug=slug)
    context = {
        'ondecomer': ondecomer
    }
    return render(request, 'ondecomer/slide.html', context)

ondeficar/views.py
# coding=utf-8

from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import OndeFicar, CategoryOndeFicar, ImageOndeficar

# Create your views here.
class ListarListView(generic.ListView):
    model = OndeFicar
    template_name = 'ondeficar/lista.html'
    context_object_name = 'object_list'
    paginate_by = 8

    def get_context_data(self, **kwargs):
        context = super(ListarListView, self).get_context_data(**kwargs)
        context['capa'] = ImageOndeficar.objects.all()
        return context


listar = ListarListView.as_view()

class CategoryListView(generic.ListView):
    template_name = 'ondeficar/descricao.html'
    context_object_name = 'object_list'
    paginate_by = 8

    def get_queryset(self):
        return OndeFicar.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(CategoryOndeFicar, slug=self.kwargs['slug'])
        context['capa'] = ImageOndeficar.objects.all()
        return context

category = CategoryListView.as_view()

def ondeficar(request, slug):
    ondeficar = OndeFicar.objects.get(slug=slug)
    context = {
        'ondeficar': ondeficar
    }
    return render(request, 'ondeficar/slide.html', context)

    capa = ImageOndecomer.objects.all()

passeios/views.py
# coding=utf-8

from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Passeio, CategoryPasseio, ImagePasseio

# Create your views here.
class ListarListView(generic.ListView):
    model = Passeio
    template_name = 'passeios/lista.html'
    context_object_name = 'object_list'
    paginate_by = 8
    def get_context_data(self, **kwargs):
        context = super(ListarListView, self).get_context_data(**kwargs)
        context['capa'] = ImagePasseio.objects.all()
        return context


listar = ListarListView.as_view()

class CategoryListView(generic.ListView):
    template_name = 'passeios/descricao.html'
    context_object_name = 'object_list'
    paginate_by = 8

    def get_queryset(self):
        return Passeio.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(CategoryPasseio, slug=self.kwargs['slug'])
        context['capa'] = ImagePasseio.objects.all()
        return context

category = CategoryListView.as_view()

def passeio(request, slug):
    passeio = Passeio.objects.get(slug=slug)
    context = {
        'passeio': passeio
    }
    return render(request, 'passeios/slide.html', context)

praias/views.py
# coding=utf-8


from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Praia, CategoryPraia, ImagePraia


class ListarListView(generic.ListView):
    model = Praia
    template_name = 'praias/lista.html'
    context_object_name = 'object_list'
    paginate_by = 8

    def get_context_data(self, **kwargs):
        context = super(ListarListView, self).get_context_data(**kwargs)
        context['capa'] = ImagePraia.objects.all()
        return context


listar = ListarListView.as_view()

class CategoryListView(generic.ListView):
    template_name = 'praias/descricao.html'
    context_object_name = 'object_list'
    paginate_by = 8

    def get_queryset(self):
        return Praia.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(CategoryPraia, slug=self.kwargs['slug'])
        return context

category = CategoryListView.as_view()

def praia(request, slug):
    praia = Praia.objects.get(slug=slug)
    context = {
        'praia': praia
    }
    return render(request, 'praias/slide.html', context)

servicos/views.py
# coding=utf-8

from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Servico, CategoryServico, ImageServico


class ListarListView(generic.ListView):
    model = CategoryServico
    template_name = 'servicos/lista.html'
    context_object_name = 'object_list'


    def get_context_data(self, **kwargs):
        context = super(ListarListView, self).get_context_data(**kwargs)
        context['capa'] = ImageServico.objects.all()
        return context


listar = ListarListView.as_view()


class CategoryListView(generic.ListView):
    template_name = 'servicos/descricao.html'
    context_object_name = 'object_list'

    def get_queryset(self):
        return Servico.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(CategoryServico, slug=self.kwargs['slug'])
        context['capa'] = ImageServico.objects.all()
        return context

category = CategoryListView.as_view()


def servico(request, slug):
    servico = Servico.objects.get(slug=slug)
    context = {
        'servico': servico
    }
    return render(request, 'servicos/slide-servicos.html', context)

core/templates/artesanato.html
{% extends "base.html"%}
{% load thumbnail %}

{% block home %}
<div id="container" class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1" >

                    {% for foto in capa %}
                        <img id="capa" class="img-responsive" src="{{ foto.image|thumbnail_url:'image'  }}" alt="{{ foto.description }}" width="1000" height="50">
                    {% endfor %}

                {% block content %}

                {% endblock %}

        </div>
    </div>
</div>
{% endblock %}

core/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load staticfiles %}
<html lang="en">
  <head>
  <title>{% block title %}Cumuruxatiba{% endblock %}</title>
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-88345369-2', 'auto');
    ga('send', 'pageview');

    </script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{%  static 'assets/favicon.ico' %}">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->


    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'assets/estilo.css' %}">
      <link href="https://fonts.googleapis.com/css?family=Courgette" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Farsan" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Bad+Script" rel="stylesheet">



    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->


</head>
<body>
  <nav id="cabecalho" class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>

            menu
            </button>
                 <a href="{% url 'index' %}">
                        <img  src="{% static 'assets/logo1.png' %}" class="img-responsive" alt="logo-cumuruxatiba" style = "padding:10px;">
                    </a>
        </div>

                <div  class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" >
                  <ul class="nav navbar-nav navbar-right" >
                    <li ><a href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a></li>
                    <li><a href="{% url 'comochegar' %}">Como Chegar</a></li>
                    <li><a href="{% url 'ondeficar:listar' %}">Onde Ficar</a></li>

                    <li><a href="{% url 'ondecomer:listar' %}">Onde Comer</a></li>

                    <li><a href="{% url 'passeios:listar' %}">Passeios</a></li>

                    <li><a href="{% url 'praias:listar' %}">Praias</a></li>
                    <li><a href="{% url 'artesanatos:listar' %}">Compras</a></li>
                    <li><a href="{% url 'servicos:listar' %}">Serviços</a></li>


                  </ul>
                  </div>
        </div>
    </div>
  </nav>
    {% block home %}
    {% endblock %}



  <footer id="rodape">
    <div class="container" >
      <div id="contato" class="col-xs-12" >
        <p><span class="glyphicon glyphicon-envelope" aria-hidden="true">&ensp;</span> fjanuarioazevedo@gmail.com</p>

        <p>
        <span class="glyphicon glyphicon-earphone" aria-hidden="true">&ensp;</span> (73)-98847-9647 </p>
      </div>
    </div>

  </footer>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'assets/bootstrap.min.js' %}"></script>
  </body>
</html>

core/templates/comochegar.html
{% extends "base.html" %}

{% block title %}
Como Chegar | {{ block.super }}
{% endblock %}
{% block home %}
    <div id="como-chegar" class="col-md-8 col-md-offset-2">
        <h1 id="titulo-comochegar" >Como Chegar</h1>
        <div class="row" >
            <div class="col-xs-12" >
                <p> Venha conhecer nossa vila simples e humilde, essas são as opções para chegar em Cumuruxatiba.</p>
            </div>

            <div class="col-xs-12" >
                <h3>De avião</h3>

                <p>Esta opção pode ser feita tanto para Posto Seguro que fica a 210km, quanto para Teixeira de Freitas que fica a 111km e ambos podem ser concluídos pelos serviços de Ônibus, Táxi ou Traslado.</p>
            </div>

            <div class=" col-xs-12" >
                <h3>De carro</h3>
                <p>Para quem está ao norte, basta seguir pela BR 101 até Itamarajú, seguindo até Prado. Para quem está ao sul, basta seguir pela BR 101 sentido litoral até Teixeira de Freitas, segue até Alcobaça e por fim segue até o  Prado.</p>
            </div>

            <div class="col-xs-12" >
                <p>A partir de Prado, existem duas formas de se chegar a Cumuruxatiba. A estrada principal é a opção mais longa, porém com maior segurança: são 9km de asfalto e 31km na estrada de chão, normalmente bem conservada. A segunda alternativa é mais curta (32km) e oferece belíssimas paisagens, pois segue paralelamente às praias, por cima das falésias. No entanto, por ser um percurso integral de terra, o acesso fica bastante complicado em épocas chuvosas.</p>
            </div>

            <div class="col-xs-12" >
                <h3>Táxi e Traslado </h3>
                <p>Estas são boas opções e uma prática comum para quem deseja chegar um Cumuruxatiba. Estes serviços são usados tanto para emergências quanto para usufruir as belas paisagens que a vila oferece. E <a href="http://cumurupraias.com.br/servicos/táxi" target="_blank" >aqui</a> você encontra profissionais capacitados a oferecer o melhor serviço.</p>

            </div>

            <div class="col-xs-12" >
                <h3>De ônibus</h3>
                <p>Visitantes provenientes de diversas localidades do país podem chegar a Prado por meio da empresa São Geraldo (0800-704-3496), que mantém linhas diretas de Belo Horizonte, Brasília, Goiânia, Rio de Janeiro, São Paulo, entre outras. A viagem de Prado até Cumuruxatiba, dura aproximadamente uma hora, através da linha oferecida pela companhia Expresso Brasileiro.</p>
                <h5 id="h5comochegar" >Estação Rodoviária de Prado: (73) 3298-1273</h5>
            </div>
            <div class="col-xs-12" id="mapa" >
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d51302.93414147517!2d-39.22100393833336!3d-17.115967220142714!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x7344fcf910a856b%3A0x60d7e073754e63f3!2sCumuruxatiba%2C+Prado+-+BA!5e0!3m2!1spt-BR!2sbr!4v1476449346046" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        </div>
    </div>
{% endblock %}

core/templates/index.html
{% extends "base.html" %}
{% block home %}
	<div id="container1" class="container">

			<div class="col-md-10 col-md-offset-1" >
				<div  class="row" >
					<h2><strong>Cumuruxatiba</strong></h2>
					  	<h2>Onde o tempo não tem pressa e a preguiça é mais gostosa</h2>
				  	</div>

				  	<div class="row" id="unidade" >
				  		{% for item in home %}
				  		<div class="col-xs-12 " style="margin-top: 80px; ">
				  			<h2>{{ item.phrase }}</h2>
				  			<div class="thumbnail">
				  			{% if item.image %}
		                    	<img src="{{ item.image.url }}" alt="{{ item.description }}">
		                    {% endif %}
		                	</div>
						    <p id="p">{{ item.subtitle }} <a href="{{item.subtitlelink}}">{{item.subtitlepalavralink}}</a> </p>

						    <p>{{ item.content }} <a href="{{ item.link }}" target="_blank" >{{ item.palavralink }}</a> </p>


						</div>
						{% endfor %}
					</div>


					</div>
			</div>





			<div id="dica" class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
				<h1> <strong> Não deixe de:</strong></h1>
				{% for item in dica %}
					<p ><strong>-&ensp;</strong>{{ item.dica|capfirst }}</p>
				{% endfor %}
			</div>




			<div id="aviso" class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
				<h1 > <strong> Importante saber:</strong></h1 >
				{% for item in aviso %}
					<p><strong>-&ensp;</strong>{{ item.aviso|capfirst }}</p>
				{% endfor %}
			</div>
    </div>




{% endblock %}

core/templates/ondecomer.html
{% extends "base.html"%}
{% load thumbnail %}

{% block home %}
<div id="container" class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1" >

                    {% for foto in capa %}
                        <img id="capa" class="img-responsive" src="{{ foto.image|thumbnail_url:'image'  }}" alt="{{ foto.description }}" width="1000" height="50">
                    {% endfor %}

                {% block content %}

                {% endblock %}

        </div>
    </div>
</div>
{% endblock %}

core/templates/ondeficar.html
{% extends "base.html"%}
{% load thumbnail %}

{% block home %}
<div id="container" class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1" >

                    {% for foto in capa %}
                        <img id="capa" class="img-responsive" src="{{ foto.image|thumbnail_url:'image'  }}" alt="{{ foto.description }}" width="1000" height="50">
                    {% endfor %}

                {% block content %}

                {% endblock %}

        </div>
    </div>
</div>
{% endblock %}